apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: blog.kubevpro.i-consulting.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog-frontend-service
            port:
              number: 80
