apiVersion: v1
kind: Service
metadata:
  name: blog-frontend-service
  labels:
    app: blog-frontend
spec:
  type: ClusterIP
  selector:
    app: blog-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
